---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
#  - name: ubuntu-12.04
#  - name: centos-6.4
  - name: centos-6.5
    #driver:
    #  box: chef/centos-6.5

suites:
  - name: PHD_AMBARI
    driver:
      vm_hostname: phdambari.local.com
      network:
      - ["private_network",{ip: "192.168.56.200"}]
    run_list:
      - recipe[ambari::default]
    attributes:
